services:

  agent:
    build:
      dockerfile: agent/agent.dockerfile
    container_name: ""

  img2vlm:
    container_name: ""
    build:
      dockerfile: img2vlm/img2vlm.dockerfile

  es_store:
    container_name: ""

  kafka:
    container_name: ""

# Обязательно прокиньте том для эластика
volumes:
  ...

# networks
# скорее всего здесь не понадобится