services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:9.3.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic_net
    depends_on:
      elasticsearch:
        condition: service_healthy

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ES_HOST=http://elasticsearch:9200
      - ELASTICSEARCH_VERIFY_CERTS=false   # отключает проверку сертификатов
      - ELASTICSEARCH_USE_SSL=false        # явно отключает SSL (для некоторых версий)
    networks:
      - elastic_net
    restart: on-failure 
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  esdata:

networks:
  elastic_net:
    driver: bridge